#pragma once
#include "native_run.hpp"
#include "owner_tracker.hpp"
#include <unordered_set>
namespace s1 {
struct WorkProfile{std::uint64_t positive_events=0,work=0,api_calls=0;};
inline WorkProfile work_profile(const Bundle& b){pbadaptive::MemoryAccounts mem;matched::Index<matched::Arm::ObserveList>x(b.domain,pbadaptive::load_frozen_config().params,mem);x.build(b.whole.initial);WorkProfile p;for(auto st:b.whole.steps){x.erase(st.erased);p.positive_events+=x.last_work()>0;p.work+=x.last_work();x.insert(st.added);p.positive_events+=x.last_work()>0;p.work+=x.last_work();p.api_calls+=2;if(st.query){auto out=x.range(st.lo,st.hi);if(out.size()!=st.expected_count||udriver::hash_records(out)!=st.expected_hash)throw std::runtime_error("work diagnostic hash mismatch");p.positive_events+=x.last_work()>0;p.work+=x.last_work();++p.api_calls;}}if(x.values()!=b.whole.final)throw std::runtime_error("work diagnostic final mismatch");return p;}
inline bool prefix_clock_check(const Bundle& b){pbadaptive::MemoryAccounts mem;matched::Index<matched::Arm::Event,64>x(b.domain,pbadaptive::load_frozen_config().params,mem);x.build(b.whole.initial);bool registered_after_range=false;for(auto st:b.whole.steps){auto before=x.cand_size();x.erase(st.erased);x.insert(st.added);auto e=x.epoch(),ops=x.ops_in_epoch(),cand=x.cand_size();if(st.query){auto out=x.range(st.lo,st.hi);if(out.size()!=8||udriver::hash_records(out)!=st.expected_hash||x.epoch()!=e||x.ops_in_epoch()!=ops||x.cand_size()!=cand)return false;}registered_after_range|=cand>before;}return registered_after_range;}
struct MechanismEvidence{std::size_t budget=32,idle=4,cooldown=8,epoch=512,minimum=128,no_idle_scheduled=0,no_idle_cleanup=0;bool old_hot_nonempty=false,reached_budget=false,budget_stall=false,idle_recovery=false,B_promoted=false,A_return_repromoted=false,exact=false;};
inline Record key(Domain d,std::size_t slot,std::uint64_t identity){return{slot*d.stride+identity,identity};}
template<class T>inline void finish_epoch(T& x){auto epoch=x.epoch();do{x.erase(key({UINT64_C(1)<<40,4096},4095,1));if(x.tree_buckets()>32)throw std::runtime_error("budget32 exceeded during engineering trajectory");}while(x.epoch()==epoch);}
template<class T>inline void heat_bucket(T& x,Domain d,std::size_t slot,std::uint64_t row,std::size_t times=256){for(std::size_t j=0;j<times;++j){auto out=x.range(slot*d.stride+row,slot*d.stride+row+1);if(out.size()!=1)throw std::runtime_error("legal heat full record");}x.erase(key(d,slot,UINT64_C(999999999)));finish_epoch(x);}
inline MechanismEvidence mechanism_engineering(){MechanismEvidence e;Domain d{UINT64_C(1)<<40,4096};auto p=pbadaptive::load_frozen_config().params;e.budget=p.tree_budget;e.idle=p.down_idle_epochs;e.cooldown=2*p.down_idle_epochs;e.epoch=p.epoch_size;e.minimum=p.min_tree_size;
 constexpr std::size_t n=256; // Engineering scale; frozen K/d/C/epoch/min remain unchanged.
 std::vector<Record> v;std::uint64_t identity=1;for(std::size_t slot=0;slot<64;++slot)for(std::size_t j=0;j<n;++j)v.push_back(key(d,slot,identity++));std::map<std::uint64_t,std::uint64_t> ref(v.begin(),v.end());pbadaptive::MemoryAccounts mem;matched::Index<matched::Arm::Cost>x(d,p,mem);x.build(v);
 // Fill A without allowing old A to go idle: every A range is sensitive.
 for(std::size_t slot=0;slot<32;++slot){for(std::size_t a=0;a<slot;++a){auto row=a*n+n/2;x.range(a*d.stride+row,a*d.stride+row+1);}heat_bucket(x,d,slot,slot*n+n/2);}
 e.reached_budget=x.tree_buckets()==32;e.old_hot_nonempty=true;for(std::size_t slot=0;slot<32;++slot)e.old_hot_nonempty&=x.bucket_size(slot)==n&&x.is_tree(slot);
 // B credit + structural candidate at full K, A touched this same epoch.
 for(std::size_t a=0;a<32;++a){auto row=a*n+n/2;x.range(a*d.stride+row,a*d.stride+row+1);}auto old=x.promotions();heat_bucket(x,d,32,32*n+n/2);e.budget_stall=x.tree_buckets()==32&&x.promotions()==old&&!x.is_tree(32)&&x.gain_ns_of(32)>0;
 auto update_endpoint=[&](){auto first=ref.begin();auto erased=first->first;ref.erase(first);auto rec=key(d,0,identity++);ref.insert(rec);x.erase(erased);x.insert(rec);if(x.values()!=std::vector<Record>(ref.begin(),ref.end()))throw std::runtime_error("SX22 complete endpoint reference");};
 for(std::size_t j=0;j<16384;++j)update_endpoint();e.idle_recovery=x.scheduled_demotions()>0&&x.tree_buckets()==0;
 // B phase at fixed budget, preserving all old A records except bucket0 endpoints.
 for(std::size_t slot=32;slot<64;++slot){for(std::size_t a=32;a<slot;++a){auto row=a*n+n/2;x.range(a*d.stride+row,a*d.stride+row+1);}heat_bucket(x,d,slot,slot*n+n/2);}
 e.B_promoted=x.tree_buckets()==32&&x.is_tree(32);
 for(std::size_t j=0;j<16384;++j)update_endpoint();auto promotions=x.promotions();
 for(std::size_t slot=0;slot<32;++slot){for(std::size_t a=0;a<slot;++a){auto it=ref.lower_bound(a*d.stride);std::advance(it,n/2-1);x.range(it->first,it->first+1);}auto it=ref.lower_bound(slot*d.stride);std::advance(it,n/2-1);heat_bucket(x,d,slot,it->second);}
 e.A_return_repromoted=x.tree_buckets()==32&&x.promotions()>=promotions+32;e.exact=x.values()==std::vector<Record>(ref.begin(),ref.end());
 pbadaptive::MemoryAccounts no_mem;matched::Index<matched::Arm::NoIdle>no(d,p,no_mem);std::vector<Record> one(v.begin(),v.begin()+n);no.build(one);heat_bucket(no,d,0,n/2);for(std::size_t j=0;j<16;++j)finish_epoch(no);for(auto rec:one)no.erase(rec);e.no_idle_scheduled=no.scheduled_demotions();e.no_idle_cleanup=no.cleanup_demotions();return e;}
struct LatencySample{std::uint64_t api_ordinal=0,completed_units=0,epoch=0,ns=0;unsigned kind=0;std::size_t phase=0;bool conversion=false;};
enum class SnapshotReason:unsigned{Periodic=1,Phase=2,Final=4,Conversion=8};
struct ResourceSample{std::uint64_t completed_units=0,api_ordinal=0;std::size_t phase=0,trees=0,persistent=0,whole_current=0,whole_peak=0;unsigned reasons=0;std::array<std::size_t,4> current{};bool accounts_available=false,output_released=true;};
#ifdef S0_EVENT_TRACE
struct ConversionEvent{diagnostic::Event event;std::uint64_t api_latency_ns=0;};
struct Observer {
 std::vector<ConversionEvent> events;std::vector<ResourceSample> resources;std::size_t event_size=0,resource_size=0;std::uint64_t completed_units=0,ordinal=0;std::size_t phase=0;bool resource=false,overflow=false;
 owner::Owner* owned=nullptr;pbadaptive::MemoryAccounts* memory=nullptr;const void* index=nullptr;std::size_t(*tree_count)(const void*)noexcept=nullptr;bool mapped=false;
 void snapshot(unsigned reason,bool released) noexcept{if(!resource)return;ResourceSample s;s.completed_units=completed_units;s.api_ordinal=ordinal;s.phase=phase;s.trees=tree_count?tree_count(index):0;s.persistent=owned->current;s.whole_current=owned->current;s.whole_peak=owned->peak;s.reasons=reason;s.output_released=released;s.accounts_available=mapped;if(mapped)s.current={memory->pool.current,memory->buckets.current,memory->tree.current,memory->manager.current};
  // Dedup only completed-unit periodic/phase/final at same API. Event snapshots
  // remain one per event; completed_units excludes the active unfinished unit.
  if(reason!=unsigned(SnapshotReason::Conversion)&&resource_size){auto& last=resources[resource_size-1];if(!(last.reasons&unsigned(SnapshotReason::Conversion))&&last.completed_units==s.completed_units&&last.api_ordinal==s.api_ordinal){last.reasons|=reason;last.phase=phase;return;}}
  if(resource_size>=resources.size()){overflow=true;return;}resources[resource_size++]=s;
 }
};
inline thread_local Observer* active_observer=nullptr;
inline void observer_sink(const diagnostic::Event& ev)noexcept{auto o=active_observer;if(!o)return;owner::Pause pause;if(o->event_size>=o->events.size()){o->overflow=true;return;}o->events[o->event_size++]={ev,0};o->ordinal=ev.api_ordinal;o->snapshot(unsigned(SnapshotReason::Conversion),false);}
struct DiagnosticResult{NativeResult run;std::vector<LatencySample> latency;std::vector<ConversionEvent> events;std::vector<ResourceSample> resources;diagnostic::ObservationCounters observations{};std::array<double,4> quantiles{};std::size_t whole_peak=0,owner_current_after_destroy=0,owner_live_after_destroy=0;};
inline double quantile(std::vector<std::uint64_t> values,double q){if(values.empty())return 0;std::sort(values.begin(),values.end());double pos=q*(values.size()-1);auto lo=static_cast<std::size_t>(std::floor(pos)),hi=static_cast<std::size_t>(std::ceil(pos));return values[lo]+(values[hi]-values[lo])*(pos-lo);}
template<class A>DiagnosticResult diagnostic_body(const Fixture& fixture,bool resource,bool fixed){
 const auto& b=fixture.bundle;DiagnosticResult result;auto& r=result.run;const auto count=2*b.request.units+b.whole.queries;result.latency.resize(count);r.phases.reserve(b.segments.size());Observer o;o.events.resize(count+1);o.resources.resize(count+2*b.segments.size()+2);o.resource=resource;o.mapped=!A::original;pbadaptive::MemoryAccounts memory;owner::Owner owned;o.owned=&owned;o.memory=&memory;
 r.start=placement();if(fixed)validate_placement(r.start);diagnostic::reset_observation_counters();
 const auto build_begin=Clock::now();std::unique_ptr<typename A::Index>x;{owner::Scope scope(owned);x.reset(A::construct(b.domain,memory));x->build(b.whole.initial);}const auto build_end=Clock::now();r.build_ns=elapsed_ns(build_begin,build_end);
 {owner::Pause pause;if(x->values()!=b.whole.initial)throw std::runtime_error("diagnostic initial mismatch");}o.index=x.get();o.tree_count=[](const void* pointer)noexcept{return static_cast<const typename A::Index*>(pointer)->tree_buckets();};active_observer=&o;diagnostic::set_event_sink(observer_sink);
 struct SinkReset{~SinkReset(){diagnostic::set_event_sink(nullptr);active_observer=nullptr;}}reset;
 std::size_t sample=0,query_index=0;std::uint64_t ordinal=0;
 for(std::size_t phase=0;phase<b.segments.size();++phase){o.phase=phase;const auto& seg=b.segments[phase];PhaseTime pt;pt.begin=seg.begin;pt.end=seg.end;pt.queries=seg.queries;pt.returned=seg.returned;pt.name=seg.name;const auto phase_begin=Clock::now();
  for(std::size_t unit=seg.begin;unit<seg.end;++unit){const auto& st=b.whole.steps[unit];
   auto api=[&](unsigned kind,auto&& operation){o.ordinal=++ordinal;diagnostic::set_api_ordinal(ordinal);auto first=o.event_size;auto begin=Clock::now();{owner::Scope scope(owned);operation();}auto end=Clock::now();auto ns=elapsed_ns(begin,end);for(auto j=first;j<o.event_size;++j)o.events[j].api_latency_ns=ns;result.latency[sample++]={ordinal,o.completed_units,A::epoch(*x),ns,kind,phase,o.event_size!=first};};
   api(0,[&](){x->erase(st.erased);});api(1,[&](){x->insert(st.added);});if(st.query){api(2,[&](){auto output=x->range(st.lo,st.hi);if(output.size()!=st.expected_count||udriver::hash_records(output)!=st.expected_hash)throw std::runtime_error("diagnostic hash/count mismatch");if(query_index>=fixture.expected.size()||fixture.expected[query_index].api_ordinal!=ordinal||fixture.expected[query_index].records!=output)throw std::runtime_error("diagnostic full query mismatch");++query_index;r.query_hash=udriver::mix(r.query_hash,st.expected_hash);r.returned+=output.size();});}o.completed_units=unit+1;if(o.completed_units%512==0)o.snapshot(unsigned(SnapshotReason::Periodic),true);
  }pt.online_ns=elapsed_ns(phase_begin,Clock::now());r.online_ns+=pt.online_ns;r.phases.push_back(pt);o.snapshot(unsigned(SnapshotReason::Phase),true);
 }o.snapshot(unsigned(SnapshotReason::Final),true);r.api_calls=ordinal;
 {owner::Pause pause;if(x->values()!=b.whole.final)throw std::runtime_error("diagnostic final mismatch");collect_counters<A>(r,*x,memory);}const auto destroy_begin=Clock::now();x.reset();r.destroy_ns=elapsed_ns(destroy_begin,Clock::now());r.total_ns=r.build_ns+r.online_ns;r.lifecycle_ns=r.total_ns+r.destroy_ns;r.end=placement();if(fixed)validate_placement(r.end);if(o.overflow)throw std::runtime_error("observer bounded storage overflow; events cannot be dropped");r.verified=true;result.observations=diagnostic::observation_counters;result.events.assign(o.events.begin(),o.events.begin()+o.event_size);result.resources.assign(o.resources.begin(),o.resources.begin()+o.resource_size);result.whole_peak=owned.peak;result.owner_current_after_destroy=owned.current;result.owner_live_after_destroy=owned.live;std::vector<std::uint64_t> ns;ns.reserve(result.latency.size());for(auto s:result.latency)ns.push_back(s.ns);result.quantiles={quantile(ns,.5),quantile(ns,.95),quantile(ns,.99),quantile(ns,1)};if(resource&&(owned.current||owned.live))throw std::runtime_error("owner not zero after destruction");return result;
}
struct DiagnosticCall{const Fixture& f;bool resource,fixed;template<class A>DiagnosticResult operator()(){return diagnostic_body<A>(f,resource,fixed);}};
inline DiagnosticResult diagnostic_production(const Fixture& f,const std::string& method){auto mode=mode_contract().active;if(mode=="native")throw std::runtime_error("diagnostic requires separate binary");return diagnostic_dispatch(method,DiagnosticCall{f,mode=="resource",true});}
#endif
struct DiagnosticEvidence{std::size_t samples=0,promotions=0,scheduled=0,cleanup=0;double p50=0,p95=0,p99=0,maximum=0;bool production_diagnostic_trajectory=false,events_complete=false,latency_accounts_na=false,original_accounts_na=false,resource_samples=false,dedup=false,output_released=false,every_conversion_snapshot=false,owner_zero=false,whole_peak_simultaneous=false,pause_ancestry_frees=false;};
inline DiagnosticEvidence diagnostic_engineering(const std::string& evidence_dir=""){(void)evidence_dir;DiagnosticEvidence e;
#ifdef S0_EVENT_TRACE
 std::ofstream trajectory_log;if(!evidence_dir.empty()){auto dir=std::filesystem::u8path(evidence_dir);if(std::filesystem::exists(dir))throw std::runtime_error("immutable diagnostic engineering destination exists");std::filesystem::create_directories(dir);trajectory_log.open(dir/"r6_diagnostic_trajectory.csv");trajectory_log<<std::setprecision(17)<<"API_ordinal,epoch,production_tree,diagnostic_tree,production_credit_ns,diagnostic_credit_ns,production_ops,diagnostic_ops,production_W,diagnostic_W,content_equal,counters_equal,engineering_only\n";}
 Domain d{UINT64_C(1)<<40,4096};auto p=pbadaptive::load_frozen_config().params;std::vector<Record> v;for(std::uint64_t j=1;j<=2048;++j)v.push_back(key(d,0,j));pbadaptive::MemoryAccounts prodmem,diagmem;pbadaptive::Index prod(d,p,prodmem);prod.build(v);owner::Owner event_owner;std::unique_ptr<diagnostic::Index<matched::Arm::Cost>>diag_ptr;{owner::Scope scope(event_owner);diag_ptr=std::make_unique<diagnostic::Index<matched::Arm::Cost>>(d,p,diagmem);diag_ptr->build(v);}auto& diag=*diag_ptr;Observer o;o.events.resize(10000);o.resources.resize(10000);o.resource=mode_contract().active=="resource";o.owned=&event_owner;o.memory=&diagmem;o.index=&diag;o.mapped=true;o.tree_count=[](const void* x)noexcept{return static_cast<const diagnostic::Index<matched::Arm::Cost>*>(x)->tree_buckets();};active_observer=&o;diagnostic::set_event_sink(observer_sink);std::map<std::uint64_t,std::uint64_t> ref(v.begin(),v.end());std::vector<std::uint64_t> latency;std::vector<unsigned> api_kinds;std::uint64_t ordinal=0;bool trajectory=true;
 auto compare=[&](){bool content=prod.values()==diag.values()&&prod.values()==std::vector<Record>(ref.begin(),ref.end());bool counters=prod.epoch()==diag.epoch()&&prod.ops_in_epoch()==diag.ops_in_epoch()&&prod.promotions()==diag.promotions()&&prod.scheduled_demotions()==diag.scheduled_demotions()&&prod.cleanup_demotions()==diag.cleanup_demotions()&&prod.total_avoidable_work()==diag.total_avoidable_work()&&prod.tree_buckets()==diag.tree_buckets()&&prod.gain_ns_of(0)==diag.gain_ns_of(0)&&prod.cooldown_until_epoch_of(0)==diag.cooldown_until_epoch_of(0)&&prod.last_sensitive_epoch_of(0)==diag.last_sensitive_epoch_of(0);trajectory&=content&&counters;if(!evidence_dir.empty())trajectory_log<<ordinal<<','<<prod.epoch()<<','<<prod.tree_buckets()<<','<<diag.tree_buckets()<<','<<prod.gain_ns_of(0)<<','<<diag.gain_ns_of(0)<<','<<prod.ops_in_epoch()<<','<<diag.ops_in_epoch()<<','<<prod.total_avoidable_work()<<','<<diag.total_avoidable_work()<<','<<content<<','<<counters<<",true\n";};
 auto api=[&](unsigned kind,std::uint64_t lo,std::uint64_t hi=0){++ordinal;diagnostic::set_api_ordinal(ordinal);o.ordinal=ordinal;auto first=o.event_size;const auto begin=Clock::now();if(kind==0){prod.erase(lo);{owner::Scope scope(event_owner);diag.erase(lo);}ref.erase(lo);}else if(kind==1){auto r=key(d,0,lo);prod.insert(r);{owner::Scope scope(event_owner);diag.insert(r);}ref.insert(r);}else{auto a=prod.range(lo,hi);std::vector<Record> b;{owner::Scope scope(event_owner);b=diag.range(lo,hi);}trajectory&=a==b&&a==ref_range(ref,lo,hi);}auto ns=elapsed_ns(begin,Clock::now());latency.push_back(ns);api_kinds.push_back(kind);for(auto j=first;j<o.event_size;++j)o.events[j].api_latency_ns=ns;compare();};
 for(unsigned j=0;j<256;++j)api(2,1024,1025);api(0,999999);while(prod.epoch()<1)api(0,d.stride*4095+1);
 while(prod.epoch()<12)api(0,d.stride*4095+1); // ordinary scheduled demotion legal, nonempty.
 for(unsigned j=0;j<256;++j)api(2,1024,1025);api(0,999999);while(prod.epoch()<21)api(0,d.stride*4095+1);
 // Idle may have demoted at later epochs: repeat legal heat until a tree exists.
 for(unsigned attempt=0;!prod.is_tree(0)&&attempt<20;++attempt){for(unsigned j=0;j<256;++j)api(2,1024,1025);api(0,999999);auto epoch=prod.epoch();while(prod.epoch()==epoch)api(0,d.stride*4095+1);}
 for(auto r:v)api(0,r.first);diagnostic::set_event_sink(nullptr);active_observer=nullptr;e.production_diagnostic_trajectory=trajectory;e.samples=latency.size();e.p50=quantile(latency,.5);e.p95=quantile(latency,.95);e.p99=quantile(latency,.99);e.maximum=quantile(latency,1);e.events_complete=!o.overflow;for(std::size_t j=0;j<o.event_size;++j){auto ev=o.events[j];e.promotions+=ev.event.type==diagnostic::EventType::Promotion;e.scheduled+=ev.event.type==diagnostic::EventType::ScheduledDemotion;e.cleanup+=ev.event.type==diagnostic::EventType::Cleanup;e.events_complete&=ev.event.api_ordinal>0&&ev.event.api_ordinal<=latency.size()&&ev.event.slot==0&&ev.api_latency_ns>0&&ev.api_latency_ns>=ev.event.body_ns&&((ev.event.type==diagnostic::EventType::Cleanup)==(ev.event.n==0));}
 auto fixture=make_synthetic({"ENGINEERING","prefix",1,2048,1024,1,0},94001,true);const bool resource=mode_contract().active=="resource";auto measured=diagnostic_dispatch("R6",DiagnosticCall{fixture,resource,false});auto orig=diagnostic_dispatch("Original",DiagnosticCall{fixture,resource,false});e.latency_accounts_na=resource||std::all_of(measured.run.accounts.begin(),measured.run.accounts.end(),[](auto s){return s=="NA";});e.original_accounts_na=std::all_of(orig.run.accounts.begin(),orig.run.accounts.end(),[](auto s){return s=="NA";});e.owner_zero=measured.owner_current_after_destroy==0&&measured.owner_live_after_destroy==0;e.resource_samples=!resource||!measured.resources.empty();e.dedup=true;e.output_released=true;e.every_conversion_snapshot=!resource;e.whole_peak_simultaneous=!resource;e.pause_ancestry_frees=!resource;
 if(resource){std::size_t conversions=0;std::set<std::uint64_t> periodic_units;std::unordered_set<std::uint64_t> after;for(auto s:measured.resources){if(s.reasons&unsigned(SnapshotReason::Conversion)){++conversions;continue;}if(s.reasons&unsigned(SnapshotReason::Periodic))periodic_units.insert(s.completed_units);e.output_released&=s.output_released;e.dedup&=after.insert(s.api_ordinal).second;e.resource_samples&=s.trees<=32&&s.persistent>=s.current[0]+s.current[1]+s.current[2]+s.current[3]&&s.whole_peak>=s.whole_current;}e.resource_samples&=periodic_units==std::set<std::uint64_t>{512,1024}&&measured.resources.back().completed_units==1024&&measured.resources.back().reasons==(unsigned(SnapshotReason::Periodic)|unsigned(SnapshotReason::Phase)|unsigned(SnapshotReason::Final));e.every_conversion_snapshot=conversions==measured.events.size()&&o.resource_size==o.event_size;for(std::size_t j=0;j<o.resource_size;++j){auto snap=o.resources[j];e.every_conversion_snapshot&=snap.api_ordinal==o.events[j].event.api_ordinal&&snap.persistent>=snap.current[0]+snap.current[1]+snap.current[2]+snap.current[3]&&snap.trees<=32;}owner::Owner scoped;void* pointer=nullptr;{owner::Scope s(scoped);pointer=::operator new(80);{owner::Pause pause;void* ignored=::operator new(1000);::operator delete(ignored);}}{owner::Pause pause;::operator delete(pointer);}e.pause_ancestry_frees=scoped.current==0&&scoped.live==0&&scoped.allocations==1&&scoped.frees==1&&scoped.peak==80;owner::Owner nonoverlap;{owner::Scope scope(nonoverlap);void* a=::operator new(80);::operator delete(a);void* b=::operator new(120);::operator delete(b);}const auto controls_before=owner::live_states;void* delayed=nullptr;{owner::Owner short_lived;owner::Scope scope(short_lived);delayed=::operator new(64);}e.pause_ancestry_frees&=owner::live_states==controls_before+1;{owner::Pause pause;::operator delete(delayed);}e.pause_ancestry_frees&=owner::live_states==controls_before;e.whole_peak_simultaneous=e.pause_ancestry_frees&&nonoverlap.current==0&&nonoverlap.peak==120&&nonoverlap.peak<80+120&&measured.whole_peak>=measured.resources.back().persistent;}
 diag_ptr.reset();e.owner_zero&=event_owner.current==0&&event_owner.live==0;
 if(!evidence_dir.empty()){
  auto dir=std::filesystem::u8path(evidence_dir);std::ofstream events(dir/"conversion_events.csv"),samples(dir/"latency_samples.csv"),resource_log(dir/"conversion_resource.csv");
  events<<"type,API_ordinal,epoch,slot,n,body_ns,api_latency_ns,clock_quantized_zero,engineering_only\n";
  for(std::size_t j=0;j<o.event_size;++j){auto ev=o.events[j];events<<(ev.event.type==diagnostic::EventType::Promotion?"promotion":ev.event.type==diagnostic::EventType::ScheduledDemotion?"scheduled":"cleanup")<<','<<ev.event.api_ordinal<<','<<ev.event.epoch<<','<<ev.event.slot<<','<<ev.event.n<<','<<ev.event.body_ns<<','<<ev.api_latency_ns<<','<<(ev.event.body_ns==0)<<",true\n";}
  samples<<"API_ordinal,API_type,ns,engineering_only\n";for(std::size_t j=0;j<latency.size();++j)samples<<j+1<<','<<(api_kinds[j]==0?"erase":api_kinds[j]==1?"insert":"range")<<','<<latency[j]<<",true\n";
  resource_log<<"API_ordinal,tree_buckets,persistent_requested_bytes,pool,buckets,tree,manager,whole_peak,snapshot_reason,engineering_only\n";for(std::size_t j=0;j<o.resource_size;++j){auto snap=o.resources[j];resource_log<<snap.api_ordinal<<','<<snap.trees<<','<<snap.persistent;for(auto bytes:snap.current)resource_log<<','<<bytes;resource_log<<','<<snap.whole_peak<<",conversion,true\n";}trajectory_log.close();if(!events||!samples||!resource_log)throw std::runtime_error("engineering evidence output failed");
  std::ofstream periodic(dir/"periodic_resource.csv");periodic<<"completed_units,API_ordinal,tree_buckets,persistent_requested_bytes,pool,buckets,tree,manager,whole_current,whole_peak,snapshot_reason_bits,output_released,engineering_only\n";for(auto snap:measured.resources){periodic<<snap.completed_units<<','<<snap.api_ordinal<<','<<snap.trees<<','<<snap.persistent;for(auto bytes:snap.current)periodic<<','<<bytes;periodic<<','<<snap.whole_current<<','<<snap.whole_peak<<','<<snap.reasons<<','<<snap.output_released<<",true\n";}if(!periodic)throw std::runtime_error("periodic resource evidence write failed");
 }
#endif
 return e;}
}
