#pragma once
#include "workloads.hpp"
#include <set>
namespace s1 {
struct Json {
 enum class Kind{Object,Array,String,Number,Boolean,Null};Kind kind=Kind::Null;std::string value;std::map<std::string,Json> object;std::vector<Json> array;
 const Json& at(const std::string& k)const{auto it=object.find(k);if(kind!=Kind::Object||it==object.end())throw std::runtime_error("missing metadata field "+k);return it->second;}
 std::string string()const{if(kind!=Kind::String)throw std::runtime_error("metadata string type");return value;}
 std::uint64_t number()const{if(kind!=Kind::Number)throw std::runtime_error("metadata integer type");return udriver::strict_u64(value);}
 bool boolean()const{if(kind!=Kind::Boolean)throw std::runtime_error("metadata boolean type");return value=="true";}
};
class JsonReader {
 const std::string& text_;std::size_t pos_=0;
 void space(){while(pos_<text_.size()&&std::isspace(static_cast<unsigned char>(text_[pos_])))++pos_;}
 char get(){if(pos_==text_.size())throw std::runtime_error("JSON truncated");return text_[pos_++];}
 std::string str(){if(get()!='\"')throw std::runtime_error("JSON string expected");std::string s;for(;;){auto c=get();if(c=='\"')return s;if(static_cast<unsigned char>(c)<32)throw std::runtime_error("JSON control character");if(c=='\\'){c=get();if(c=='n')c='\n';else if(c=='r')c='\r';else if(c=='t')c='\t';else if(c!='\"'&&c!='\\'&&c!='/')throw std::runtime_error("JSON unsupported escape");}s+=c;}}
 Json value(){space();Json j;if(pos_==text_.size())throw std::runtime_error("JSON value missing");auto c=text_[pos_];if(c=='{'){++pos_;j.kind=Json::Kind::Object;space();if(text_[pos_]=='}'){++pos_;return j;}for(;;){space();auto key=str();space();if(get()!=':')throw std::runtime_error("JSON colon");if(!j.object.emplace(key,value()).second)throw std::runtime_error("JSON duplicate key");space();auto end=get();if(end=='}')return j;if(end!=',')throw std::runtime_error("JSON object separator");}}
 if(c=='['){++pos_;j.kind=Json::Kind::Array;space();if(text_[pos_]==']'){++pos_;return j;}for(;;){j.array.push_back(value());space();auto end=get();if(end==']')return j;if(end!=',')throw std::runtime_error("JSON array separator");}}
 if(c=='\"'){j.kind=Json::Kind::String;j.value=str();return j;}auto begin=pos_;while(pos_<text_.size()&&std::string(",]} \r\n\t").find(text_[pos_])==std::string::npos)++pos_;j.value=text_.substr(begin,pos_-begin);if(j.value=="true"||j.value=="false")j.kind=Json::Kind::Boolean;else if(j.value=="null")j.kind=Json::Kind::Null;else{j.kind=Json::Kind::Number;udriver::strict_u64(j.value);}return j;}
public:explicit JsonReader(const std::string& s):text_(s){}Json parse(){auto j=value();space();if(pos_!=text_.size())throw std::runtime_error("JSON trailing bytes");return j;}
};
inline Json read_json(const std::filesystem::path& path){std::ifstream file(path,std::ios::binary);if(!file)throw std::runtime_error("metadata unavailable");std::string text((std::istreambuf_iterator<char>(file)),{});return JsonReader(text).parse();}
struct VerifiedCache{Fixture fixture;Json meta;std::filesystem::path cache,expected,metadata;std::string cache_sha,expected_sha,metadata_sha;};
inline void validate_case_schedule(const std::string& id,const Bundle& b){auto spec=case_spec(id);if(b.whole.steps.size()!=spec.units)throw std::runtime_error("registered total update count mismatch");std::vector<std::size_t> lengths;std::vector<std::string> names;std::vector<std::uint64_t> q,c;
 if(id=="F04"){lengths={87381,87381,87382};names={"sparse_before","shuffle","sparse_after"};q={256,8,256};c={256,0,256};if(b.query_period||b.cancel_period)throw std::runtime_error("F04 aggregate q/c must be0; segments authoritative");}
 else if(id=="M01"){lengths={32768,16384,32768,16384,32768};names={"A_hot","idle1","B_hot","idle2","A_return"};q.assign(5,spec.units+1);c.assign(5,0);if(b.query_period!=spec.units+1||b.cancel_period)throw std::runtime_error("M01 registered aggregate q/c mismatch");}
 else{lengths={spec.units};names={spec.pattern};q={spec.q?spec.q:spec.units+1};c={spec.c};if(b.query_period!=q[0]||b.cancel_period!=spec.c)throw std::runtime_error("registered aggregate q/c mismatch");}
 if(b.segments.size()!=lengths.size())throw std::runtime_error("registered phase count mismatch");std::size_t begin=0;for(std::size_t j=0;j<lengths.size();++j){const auto& seg=b.segments[j];bool shuffled=id=="F04"&&j==1;if(seg.begin!=begin||seg.end!=begin+lengths[j]||seg.name!=names[j]||seg.query_period!=q[j]||seg.cancel_period!=c[j]||seg.shuffle_incoming!=shuffled||seg.random_every_delete!=shuffled)throw std::runtime_error("registered phase boundary/name/q/c/shuffle mismatch");begin=seg.end;}
}
inline VerifiedCache verify_cache(const std::filesystem::path& path,const std::string& expected_cache_sha,bool allow_engineering=false){
 VerifiedCache v;v.cache=std::filesystem::absolute(path);v.expected=v.cache.parent_path()/"cache.expected.bin";v.metadata=v.cache.parent_path()/"cache.meta.json";require_sha(v.cache,expected_cache_sha);v.cache_sha=expected_cache_sha;v.metadata_sha=sha_file(v.metadata);v.meta=read_json(v.metadata);auto& m=v.meta;
 const std::set<std::string> keys={"schema","case_id","profile","engineering_only","seed","N","U","domain","phase_lengths","q","c","phase_q","phase_c","API_calls","queries","source_rows","month","days","ordered","dataset_sha","protocol_sha","generator_sha","cache_sha","expected_sha","initial_sha","final_sha","selection_input_identity"};if(m.object.size()!=keys.size())throw std::runtime_error("metadata schema field count mismatch");for(auto kv:m.object)if(!keys.count(kv.first))throw std::runtime_error("unknown metadata field");if(m.at("schema").string()!="S1.cache.v1")throw std::runtime_error("metadata schema mismatch");
 bool engineering=m.at("engineering_only").boolean();if(engineering&&!allow_engineering)throw std::runtime_error("engineering cache rejected by production run");v.fixture.case_id=m.at("case_id").string();v.fixture.profile=m.at("profile").string();v.fixture.engineering=engineering;
 auto& b=v.fixture.bundle;b=frozen_read_cache(v.cache);if(!engineering)validate_registered(v.fixture.case_id,b.request.seed,v.fixture.profile);require_sha(protocol_path(),protocol_sha);if(b.request.protocol_sha!=protocol_sha||m.at("protocol_sha").string()!=protocol_sha)throw std::runtime_error("protocol binding mismatch");
 if(m.at("generator_sha").string()!=sha_file(generator_path()))throw std::runtime_error("generator source binding mismatch");if(m.at("cache_sha").string()!=expected_cache_sha)throw std::runtime_error("cache metadata SHA mismatch");v.expected_sha=m.at("expected_sha").string();require_sha(v.expected,v.expected_sha);
 if(b.request.seed!=m.at("seed").number()||b.request.initial!=m.at("N").number()||b.request.units!=m.at("U").number()||b.domain.stride!=m.at("domain").at("stride").number()||b.domain.span!=m.at("domain").at("span").number()||b.source_rows!=m.at("source_rows").number()||b.request.month!=m.at("month").string()||b.request.days!=m.at("days").number()||b.ordered!=m.at("ordered").boolean())throw std::runtime_error("cache metadata request/domain mismatch");
 if(b.request.dataset_sha!=m.at("dataset_sha").string()||b.request.dataset_sha!=(b.request.days==31?dataset_sha:protocol_sha)||record_sha(b.whole.initial)!=m.at("initial_sha").string()||record_sha(b.whole.final)!=m.at("final_sha").string()||2*b.request.units+b.whole.queries!=m.at("API_calls").number()||b.whole.queries!=m.at("queries").number())throw std::runtime_error("cache metadata input/reference mismatch");
 if(m.at("selection_input_identity").string()!=v.fixture.case_id+":"+std::to_string(b.request.seed)+":"+v.cache_sha)throw std::runtime_error("selection input identity mismatch");auto& lengths=m.at("phase_lengths").array;auto& qs=m.at("phase_q").array;auto& cs=m.at("phase_c").array;if(lengths.size()!=b.segments.size()||qs.size()!=lengths.size()||cs.size()!=lengths.size())throw std::runtime_error("metadata phase array shape");for(std::size_t j=0;j<lengths.size();++j)if(lengths[j].number()!=b.segments[j].end-b.segments[j].begin||qs[j].number()!=(b.segments[j].query_period>b.request.units?0:b.segments[j].query_period)||cs[j].number()!=b.segments[j].cancel_period)throw std::runtime_error("metadata phase q/c/length mismatch");if(m.at("q").number()!=(b.query_period>b.request.units?0:b.query_period)||m.at("c").number()!=b.cancel_period)throw std::runtime_error("metadata aggregate q/c mismatch");
 if(!engineering){auto spec=case_spec(v.fixture.case_id);if(b.request.initial!=spec.n*spec.buckets||b.request.units!=spec.units||b.request.workload!=spec.pattern||b.request.days!=(spec.public_data?31:0)||b.source_rows!=(spec.public_data?2964617:spec.n*spec.buckets)||b.domain.stride!=(spec.public_data?2964618:UINT64_C(1)<<40)||b.domain.span!=(spec.public_data?2678400:4096)||b.ordered!=(v.fixture.case_id!="F04"))throw std::runtime_error("cache case norm mismatch");validate_case_schedule(v.fixture.case_id,b);if(spec.public_data)require_sha(public_path(),dataset_sha);}
 require_sha(v.cache,v.cache_sha);require_sha(v.expected,v.expected_sha);require_sha(v.metadata,v.metadata_sha);return v;
}
inline void reverify_cache(const VerifiedCache& v){require_sha(v.cache,v.cache_sha);require_sha(v.expected,v.expected_sha);require_sha(v.metadata,v.metadata_sha);require_sha(protocol_path(),protocol_sha);if(v.fixture.bundle.request.dataset_sha==dataset_sha)require_sha(public_path(),dataset_sha);}
inline std::vector<std::pair<std::string,std::filesystem::path>> source_bundle_files(){std::vector<std::pair<std::string,std::filesystem::path>> files;for(auto name:{"adapters.hpp","diagnostic_index.hpp","diagnostic_run.hpp","matched_index.hpp","metadata.hpp","native_run.hpp","owner_tracker.hpp","s1_driver.cpp","sha256.hpp","workloads.hpp"})files.push_back({std::string("S1/src/")+name,s1_dir()/"src"/name});auto root=s1_dir().parent_path().parent_path();for(auto name:{"final/adaptive_poolhbi_final.hpp","final/adaptive_types.hpp","final/shared_allocator.hpp","final/frozen_config.hpp","final_experiments/driver_core.hpp","final_experiments/trace_cache.hpp","final_experiments/legacy/generators.hpp","final_experiments/legacy/pool_index.hpp","final_experiments/legacy/public_index.hpp"})files.push_back({std::string("adaptive_poolhbi/")+name,root/"adaptive_poolhbi"/name});std::sort(files.begin(),files.end(),[](auto a,auto b){return a.first<b.first;});return files;}
inline std::string source_bundle_sha(){std::string text;for(auto file:source_bundle_files())text+=file.first+"\n"+sha_file(file.second)+"\n";return sha_text(text);}
inline std::string method_config(const std::string& method){validate_method(method);return "{\"schema\":\"S1.method.v1\",\"method\":"+json_quote(method)+",\"mode\":"+json_quote(mode_contract().active)+",\"credit_unit\":"+json_quote(method.rfind("M_EVENT_",0)==0?"event":method.rfind("M_FIXED_",0)==0?"none":method=="Original"||method=="M_LIST"?"NA":"ns")+",\"frozen_R6\":"+pbadaptive::fingerprint_json(pbadaptive::load_frozen_config())+"}";}
}
