#include "native_run.hpp"
#include "diagnostic_run.hpp"
#include "metadata.hpp"
#include <iostream>
#include <psapi.h>
#ifndef S1_SOURCE_BUNDLE_SHA
#define S1_SOURCE_BUNDLE_SHA "UNBOUND_TEST_ONLY"
#endif
namespace s1 {
inline std::filesystem::path binary_path(){std::vector<wchar_t> buf(32768);auto count=GetModuleFileNameW(nullptr,buf.data(),static_cast<DWORD>(buf.size()));if(!count||count==buf.size())throw std::runtime_error("binary path unavailable");return std::filesystem::path(std::wstring(buf.data(),count));}
inline void source_bound(){auto actual=source_bundle_sha();if(actual!=S1_SOURCE_BUNDLE_SHA)throw std::runtime_error("compiled source bundle changed/unbound");require_sha(protocol_path(),protocol_sha);}
using Options=std::map<std::string,std::string>;
inline Options options(const std::vector<std::string>& args,const std::set<std::string>& allowed){Options v;for(std::size_t i=1;i<args.size();i+=2){if(i+1==args.size()||!allowed.count(args[i])||!v.emplace(args[i],args[i+1]).second)throw std::invalid_argument("unknown/missing/duplicate parameter");}return v;}
inline const std::string& opt(const Options& o,const std::string& k){auto it=o.find(k);if(it==o.end()||it->second.empty())throw std::invalid_argument("required parameter "+k);return it->second;}
inline std::string csv(const std::string& s){std::string out="\"";for(char c:s){if(c=='\"')out+='\"';out+=c;}return out+'\"';}
inline void csv_row(std::ostream& out,const std::vector<std::string>& v){for(std::size_t j=0;j<v.size();++j){if(j)out<<',';out<<csv(v[j]);}out<<'\n';}
inline std::vector<std::string> identity_columns(){return {"batch_id","attempt_id","case_id","seed","pair_id","round","role","method","selected_theta","selected_h","measurement_mode","cache_sha","dataset_sha","protocol_sha","source_bundle_sha","binary_sha","config_sha","N","U","queries","API_calls","returned","query_hash","status","placement_start_mask","placement_start_cpu","placement_start_group","placement_end_mask","placement_end_cpu","placement_end_group"};}
inline std::vector<std::string> identity_values(const Options& o,const VerifiedCache& v,const std::string& method,const NativeResult& r,bool engineering){const auto& b=v.fixture.bundle;return {opt(o,"--batch-id"),opt(o,"--attempt-id"),v.fixture.case_id,std::to_string(b.request.seed),opt(o,"--pair-id"),opt(o,"--round"),opt(o,"--role"),method,method.rfind("M_EVENT_",0)==0?method.substr(8):"NA",method.rfind("M_FIXED_",0)==0?method.substr(8):"NA",mode_contract().active,v.cache_sha,b.request.dataset_sha,b.request.protocol_sha,source_bundle_sha(),sha_file(binary_path()),sha_text(method_config(method)),std::to_string(b.request.initial),std::to_string(b.request.units),std::to_string(b.whole.queries),std::to_string(r.api_calls),std::to_string(r.returned),std::to_string(r.query_hash),engineering?"ENGINEERING_CORRECTNESS_ONLY":"valid",std::to_string(r.start.process_mask),std::to_string(r.start.cpu),std::to_string(r.start.group),std::to_string(r.end.process_mask),std::to_string(r.end.cpu),std::to_string(r.end.group)};}
inline void append(std::vector<std::string>& a,const std::vector<std::string>& b){a.insert(a.end(),b.begin(),b.end());}
inline void native_csv(const std::filesystem::path& dir,const Options& o,const VerifiedCache& v,const std::string& method,const NativeResult& r,bool engineering){auto columns=identity_columns(),row=identity_values(o,v,method,r,engineering);append(columns,{"build_ns","online_ns","total_ns","destroy_ns","lifecycle_ns","total_avoidable_work","promotions","scheduled_demotions","cleanup_demotions","total_demotions","peak_tree_buckets","final_tree_buckets","cand_last","cand_max","nodes_allocated","conversion_up_ns","conversion_down_ns","conversion_failures","credit_unit"});append(row,{std::to_string(r.build_ns),std::to_string(r.online_ns),std::to_string(r.total_ns),std::to_string(r.destroy_ns),std::to_string(r.lifecycle_ns),r.work,r.promotions,r.scheduled,r.cleanup,r.demotions,r.peak_trees,r.final_trees,r.cand_last,r.cand_max,r.nodes,r.up_ns,r.down_ns,r.failures,r.credit_unit});const std::array<const char*,4> names{{"pool","buckets","tree","manager"}};for(unsigned j=0;j<4;++j){append(columns,{std::string(names[j])+"_current",std::string(names[j])+"_peak",std::string(names[j])+"_allocations",std::string(names[j])+"_frees"});if(r.accounts[j]=="NA")append(row,{"NA","NA","NA","NA"});else{auto s=r.account_stats[j];append(row,{std::to_string(s.current),std::to_string(s.peak),std::to_string(s.allocations),std::to_string(s.frees)});}}
 std::ofstream raw(dir/"raw_native.csv");csv_row(raw,columns);csv_row(raw,row);std::ofstream phase(dir/"phase.csv");columns=identity_columns();append(columns,{"phase","begin_unit","end_unit","phase_query_count","phase_returned","online_ns"});csv_row(phase,columns);for(auto p:r.phases){row=identity_values(o,v,method,r,engineering);append(row,{p.name,std::to_string(p.begin),std::to_string(p.end),std::to_string(p.queries),std::to_string(p.returned),std::to_string(p.online_ns)});csv_row(phase,row);}if(!raw||!phase)throw std::runtime_error("CSV write failed");}
#ifdef S0_EVENT_TRACE
inline const char* event_name(diagnostic::EventType type){return type==diagnostic::EventType::Promotion?"promotion":type==diagnostic::EventType::ScheduledDemotion?"scheduled":"cleanup";}
inline std::string snapshot_name(unsigned bits){std::string s;for(auto pair:{std::pair<unsigned,const char*>{1,"periodic512"},{2,"phase"},{4,"final"},{8,"conversion"}})if(bits&pair.first){if(!s.empty())s+='|';s+=pair.second;}return s;}
inline void diagnostic_csv(const std::filesystem::path& dir,const Options& o,const VerifiedCache& v,const std::string& method,const DiagnosticResult& d,bool engineering){auto base=identity_columns(),id=identity_values(o,v,method,d.run,engineering);auto columns=base;append(columns,{"type","API_ordinal","epoch","slot","n","conversion_body_ns","api_latency_ns"});std::ofstream events(dir/"conversion_events.csv");csv_row(events,columns);for(auto ev:d.events){auto row=id;append(row,{event_name(ev.event.type),std::to_string(ev.event.api_ordinal),std::to_string(ev.event.epoch),std::to_string(ev.event.slot),std::to_string(ev.event.n),std::to_string(ev.event.body_ns),std::to_string(ev.api_latency_ns)});csv_row(events,row);}
 std::ofstream latency(dir/"latency.csv");columns=base;append(columns,{"API_type","API_ordinal","epoch","ns","conversion","phase","completed_units_before_active_api"});csv_row(latency,columns);for(auto sample:d.latency){auto row=id;append(row,{sample.kind==0?"erase":sample.kind==1?"insert":"range",std::to_string(sample.api_ordinal),std::to_string(sample.epoch),std::to_string(sample.ns),sample.conversion?"true":"false",std::to_string(sample.phase),std::to_string(sample.completed_units)});csv_row(latency,row);}
 std::ofstream summary(dir/"latency_summary.json");std::vector<std::uint64_t> bodies,apis;for(auto ev:d.events){bodies.push_back(ev.event.body_ns);apis.push_back(ev.api_latency_ns);}auto observation=[&](std::uint64_t x){return method=="Original"?json_quote("NA"):std::to_string(x);};auto resource_value=[](std::uint64_t x){return mode_contract().active=="resource"?std::to_string(x):json_quote("NA");};summary<<"{\"measurement_mode\":"<<json_quote(mode_contract().active)<<",\"engineering_only\":"<<(engineering?"true":"false")<<",\"samples\":"<<d.latency.size()<<",\"p50\":"<<d.quantiles[0]<<",\"p95\":"<<d.quantiles[1]<<",\"p99\":"<<d.quantiles[2]<<",\"max\":"<<d.quantiles[3]<<",\"conversion_events\":"<<d.events.size()<<",\"diagnostic_list_work\":"<<observation(d.observations.list_work)<<",\"range_buffers\":"<<observation(d.observations.range_buffers)<<",\"epoch_scans\":"<<observation(d.observations.epoch_scans)<<",\"candidate_visits\":"<<observation(d.observations.candidate_visits)<<",\"conversion_body_p50\":"<<quantile(bodies,.5)<<",\"conversion_body_p99\":"<<quantile(bodies,.99)<<",\"conversion_body_max\":"<<quantile(bodies,1)<<",\"conversion_api_p99\":"<<quantile(apis,.99)<<",\"whole_peak_requested_bytes\":"<<resource_value(d.whole_peak)<<",\"owner_current_after_destroy\":"<<resource_value(d.owner_current_after_destroy)<<",\"owner_live_after_destroy\":"<<resource_value(d.owner_live_after_destroy)<<",\"resource_metric\":"<<json_quote(mode_contract().active=="resource"?"simultaneous_live_requested_bytes_not_hardware_RSS":"NA")<<"}\n";
 if(mode_contract().active=="resource"){std::ofstream resource(dir/"resource.csv");columns=base;append(columns,{"completed_unit","phase","snapshot_reason","API_ordinal","unit_semantics","output_released","pool_current","buckets_current","tree_current","manager_current","persistent_requested_bytes","whole_current","whole_peak","tree_buckets"});csv_row(resource,columns);for(auto s:d.resources){auto row=id;append(row,{std::to_string(s.completed_units),std::to_string(s.phase),snapshot_name(s.reasons),std::to_string(s.api_ordinal),(s.reasons&8)?"completed_before_active_api":"completed_after_output_release",s.output_released?"true":"false"});for(unsigned j=0;j<4;++j)row.push_back(s.accounts_available?std::to_string(s.current[j]):"NA");append(row,{std::to_string(s.persistent),std::to_string(s.whole_current),std::to_string(s.whole_peak),std::to_string(s.trees)});csv_row(resource,row);}if(!resource)throw std::runtime_error("resource write failed");}if(!events||!latency||!summary)throw std::runtime_error("diagnostic output failed");}
#endif
inline void execute_run(const Options& opts,bool engineering=false){source_bound();auto method=opt(opts,"--method");validate_method(method);for(auto k:{"--batch-id","--attempt-id","--pair-id","--round","--role"}){auto str=opt(opts,k);if(str.find_first_of("\r\n")!=std::string::npos)throw std::runtime_error("identity newline rejected");}auto round=udriver::strict_u64(opt(opts,"--round"));if(round<1||round>2)throw std::runtime_error("round requires1/2");auto role=opt(opts,"--role");if(role!="A"&&role!="B")throw std::runtime_error("role requires A/B");auto v=verify_cache(std::filesystem::u8path(opt(opts,"--cache")),opt(opts,"--cache-sha"),engineering);auto out=std::filesystem::u8path(opt(opts,"--output"));if(std::filesystem::exists(out))throw std::runtime_error("immutable output destination exists");validate_placement(placement());std::filesystem::create_directories(out);
 try{NativeResult r;
#ifdef S0_EVENT_TRACE
  v.fixture.expected=read_expected(v.expected,v.fixture.bundle.whole.queries);auto d=diagnostic_production(v.fixture,method);r=d.run;native_csv(out,opts,v,method,r,engineering);diagnostic_csv(out,opts,v,method,d,engineering);
#else
  r=native_production(v.fixture.bundle,method);native_csv(out,opts,v,method,r,engineering);
#endif
  if(!r.build_ns||!r.online_ns||!r.total_ns||!r.destroy_ns||!r.lifecycle_ns||std::any_of(r.phases.begin(),r.phases.end(),[](auto phase){return !phase.online_ns;}))throw std::runtime_error("nonpositive measured component");reverify_cache(v);source_bound();std::ofstream config(out/"config.json");config<<method_config(method)<<'\n';std::ofstream receipt(out/"run_receipt.json");receipt<<"{\"schema\":\"S1.run.v1\",\"status\":"<<json_quote(engineering?"ENGINEERING_CORRECTNESS_ONLY":"valid")<<",\"engineering_only\":"<<(engineering?"true":"false")<<",\"measurement_mode\":"<<json_quote(mode_contract().active)<<",\"cache_sha_before\":"<<json_quote(v.cache_sha)<<",\"cache_sha_after\":"<<json_quote(sha_file(v.cache))<<",\"expected_sha_before\":"<<json_quote(v.expected_sha)<<",\"expected_sha_after\":"<<json_quote(sha_file(v.expected))<<",\"metadata_sha\":"<<json_quote(v.metadata_sha)<<",\"binary_sha\":"<<json_quote(sha_file(binary_path()))<<",\"source_bundle_sha\":"<<json_quote(source_bundle_sha())<<",\"config_sha\":"<<json_quote(sha_text(method_config(method)))<<",\"protocol_sha\":"<<json_quote(protocol_sha)<<",\"phase_clock_native\":\"fixed_phase_boundaries_only\",\"actual_affinity_mask_start\":"<<r.start.process_mask<<",\"actual_affinity_mask_end\":"<<r.end.process_mask<<",\"actual_cpu_start\":"<<r.start.cpu<<",\"actual_cpu_end\":"<<r.end.cpu<<",\"account_availability\":"<<json_quote(mode_contract().active=="resource"&&method!="Original"?"matched four accounts enabled":"NA")<<"}\n";if(!receipt||!config)throw std::runtime_error("receipt write failure");std::cout<<"verified "<<mode_contract().active<<" "<<method<<" "<<(engineering?"ENGINEERING_CORRECTNESS_ONLY":"valid")<<'\n';}
 catch(const std::exception& err){std::ofstream failure(out/"failure.json");failure<<"{\"status\":\"invalid_attempt\",\"error\":"<<json_quote(err.what())<<"}\n";throw;}}
inline int driver_main(const std::vector<std::string>& args){if(args.empty())throw std::invalid_argument("command required");source_bound();if(args[0]=="describe"){auto o=options(args,{"--method"});auto method=opt(o,"--method");auto placement_now=placement();std::cout<<"{\"schema\":\"S1.describe.v1\",\"measurement_mode\":"<<json_quote(mode_contract().active)<<",\"method\":"<<json_quote(method)<<",\"config_sha\":"<<json_quote(sha_text(method_config(method)))<<",\"source_bundle_sha\":"<<json_quote(source_bundle_sha())<<",\"generator_sha\":"<<json_quote(sha_file(generator_path()))<<",\"binary_sha\":"<<json_quote(sha_file(binary_path()))<<",\"protocol_sha\":"<<json_quote(protocol_sha)<<",\"process_mask\":"<<placement_now.process_mask<<",\"logical_cpu\":"<<placement_now.cpu<<",\"native_work_available\":"<<((method=="M_LIST"||method=="Original")?"false":"true")<<",\"four_accounts_available\":"<<(mode_contract().active=="resource"&&method!="Original"?"true":"false")<<",\"config\":"<<method_config(method)<<"}\n";return 0;}
 if(args[0]=="prepare"){auto o=options(args,{"--case","--seed","--profile","--protocol-sha","--output"});if(opt(o,"--protocol-sha")!=protocol_sha)throw std::runtime_error("requested protocol actual SHA mismatch");auto seed=udriver::strict_u64(opt(o,"--seed"));if(seed>UINT_MAX)throw std::runtime_error("seed overflow");auto f=registered_fixture(opt(o,"--case"),static_cast<unsigned>(seed),opt(o,"--profile"));write_fixture(f,std::filesystem::u8path(opt(o,"--output")));source_bound();std::cout<<"prepared "<<f.case_id<<" "<<seed<<" no timing experiment\n";return 0;}
 if(args[0]=="run"){auto o=options(args,{"--cache","--cache-sha","--method","--output","--batch-id","--attempt-id","--pair-id","--round","--role"});execute_run(o);return 0;}
 // Fixed-affinity correctness fixture only. No size, seed, mask, or method knob.
 if(args[0]=="selftest"){auto o=options(args,{"--output"});auto dir=std::filesystem::u8path(opt(o,"--output"));if(std::filesystem::exists(dir))throw std::runtime_error("immutable selftest destination exists");validate_placement(placement());auto f=engineering_fixture(128,16);f.profile="engineering";write_fixture(f,dir/"input");for(const auto& method:std::vector<std::string>{"M_LIST","R6","Original"}){Options run={{"--cache",path_utf8(std::filesystem::absolute(dir/"input/cache.bin"))},{"--cache-sha",sha_file(dir/"input/cache.bin")},{"--method",method},{"--output",path_utf8(dir/method)},{"--batch-id","engineering-selftest"},{"--attempt-id","1"},{"--pair-id","correctness-only"},{"--round","1"},{"--role","A"}};execute_run(run,true);}return 0;}
 throw std::invalid_argument("unknown command");}
}
int wmain(int argc,wchar_t** argv){try{std::vector<std::string> args;for(int i=1;i<argc;++i)args.push_back(s1::path_utf8(std::filesystem::path(argv[i])));return s1::driver_main(args);}catch(const std::exception& e){std::cerr<<"driver rejected: "<<e.what()<<'\n';return 2;}}
