#pragma once
#include "../../../adaptive_poolhbi/final_experiments/driver_core.hpp"
#include "sha256.hpp"
#include <map>
namespace s1 {
using udriver::Record;using udriver::Domain;using udriver::Bundle;using udriver::Step;using udriver::PhaseSegment;
inline constexpr const char* protocol_sha="bdb24556642d4137ab485befac9758b0abb04d933ebe5a3493b03d981cd9118a";
inline constexpr const char* dataset_sha="070d1574bf455dce54daad47a64ecda9176bc6cd1af771d84d8b0c3de1b0da7d";
inline std::filesystem::path s1_dir(){return std::filesystem::u8path(__FILE__).lexically_normal().parent_path().parent_path();}
inline std::filesystem::path protocol_path(){return s1_dir().parent_path()/"S0"/"S0_preregistration.json";}
inline std::filesystem::path public_path(){return s1_dir().parent_path().parent_path()/std::filesystem::u8path(u8"公开数据实验")/"data"/"tlc_2024_01_uint64.bin";}
inline std::filesystem::path generator_path(){return std::filesystem::u8path(__FILE__).lexically_normal();}
struct CacheDirectory{std::filesystem::path prior;explicit CacheDirectory(const std::filesystem::path& dir):prior(std::filesystem::current_path()){std::filesystem::current_path(dir);}~CacheDirectory(){std::filesystem::current_path(prior);}};
inline void frozen_write_cache(const std::filesystem::path& path,const Bundle& bundle){auto absolute=std::filesystem::absolute(path);CacheDirectory scope(absolute.parent_path());udriver::write_cache(path_utf8(absolute.filename()),bundle);}
inline Bundle frozen_read_cache(const std::filesystem::path& path){auto absolute=std::filesystem::absolute(path);CacheDirectory scope(absolute.parent_path());return udriver::read_cache(path_utf8(absolute.filename()));}
struct Expected{std::uint64_t api_ordinal=0;std::vector<Record> records;};
struct Fixture{Bundle bundle;std::vector<Expected> expected;std::string case_id,profile;bool engineering=false;};
struct CaseSpec{std::string id,pattern;std::size_t buckets,n,units;std::uint64_t q,c;bool public_data=false;};
inline const std::vector<CaseSpec>& case_registry(){static const std::vector<CaseSpec> v={
 {"D01","endpoint",1,256,512,0,0},{"D02","endpoint",1,4096,8192,0,0},{"D03","low",1,256,512,0,0},{"D04","low",1,4096,8192,0,0},{"D05","high",1,256,512,0,0},{"D06","high",1,4096,8192,0,0},{"D07","prefix",1,256,512,1,0},{"D08","prefix",1,4096,8192,1,0},{"D09","competition",64,256,512,0,0},{"D10","competition",64,1024,8192,0,0},
 {"F01","ordered_sparse",1,262144,262144,256,0,true},{"F02","ordered_sparse_cancel",1,262144,262144,256,256,true},{"F03","ordered_dense",1,262144,262144,1,0,true},{"F04","s0_sparse_shuffle_sparse_v1",1,262144,262144,0,0,true},{"F05","low",1,8192,4096,0,0},{"F06","high",1,8192,4096,0,0},{"F07","prefix",1,8192,4096,1,0},
 {"M01","mechanism",64,2048,131072,0,0}};return v;}
inline CaseSpec case_spec(const std::string& id){for(auto s:case_registry())if(s.id==id)return s;throw std::invalid_argument("unknown registered case");}
inline void validate_registered(const std::string& id,unsigned seed,const std::string& profile){auto s=case_spec(id);bool ok=false;
 if(profile=="dev")ok=id[0]=='D'&&seed>=90001&&seed<=90003;
 else if(profile=="final")ok=id[0]=='F'&&seed>=91001&&seed<=91010;
 else if(profile=="aa"){ok=seed==92001&&(id=="D02"||id=="D06"||id=="F01"||id=="F03"||id=="F06");}
 else if(profile=="mechanism")ok=id=="M01"&&seed>=93001&&seed<=93003;
 (void)s;if(!ok)throw std::invalid_argument("case/seed/profile outside preregistration");}
inline std::mt19937_64 synthetic_rng(unsigned seed,unsigned tag){return std::mt19937_64(UINT64_C(0x6a09e667f3bcc909)^(std::uint64_t(seed)*104729)^(std::uint64_t(tag)*UINT64_C(0x9e3779b97f4a7c15)));}
inline std::vector<Record> load_public_verified(){require_sha(public_path(),dataset_sha);std::ifstream in(public_path(),std::ios::binary);auto read=[&](){unsigned char bytes[8];in.read(reinterpret_cast<char*>(bytes),8);if(!in)throw std::runtime_error("public input truncated");std::uint64_t n=0;for(unsigned j=0;j<8;++j)n|=std::uint64_t(bytes[j])<<(8*j);return n;};auto n=read();if(n!=2964617)throw std::runtime_error("frozen public source rows mismatch");Domain d{2964618,2678400};std::vector<Record> v;v.reserve(n);for(std::uint64_t row=1;row<=n;++row){auto time=read();if(time>=d.span)throw std::runtime_error("public time outside frozen span");v.push_back({time*d.stride+row,row});}char extra;if(in.get(extra))throw std::runtime_error("public input trailing bytes");require_sha(public_path(),dataset_sha);return v;}
inline void init_geometry(Bundle& b){std::array<std::size_t,4096> loads{};auto& t=b.whole;std::uint64_t last=UINT64_MAX;for(auto r:t.initial){auto time=r.first/b.domain.stride;if(last!=time){++t.initial_distinct_times;last=time;}++loads[b.domain.slot(r.first)];}for(auto n:loads){t.initial_nonempty_buckets+=n>0;t.initial_max_bucket=std::max(t.initial_max_bucket,std::uint64_t(n));}t.initmax=t.initial.empty()?0:t.initial.back().first/b.domain.stride;}
inline std::vector<Record> ref_range(const std::map<std::uint64_t,std::uint64_t>& ref,std::uint64_t lo,std::uint64_t hi){std::vector<Record> out;for(auto it=ref.lower_bound(lo);it!=ref.end()&&it->first<hi;++it)out.emplace_back(*it);return out;}
inline void append_step(Fixture& f,PhaseSegment& seg,Step st,std::map<std::uint64_t,std::uint64_t>& ref,std::uint64_t& ordinal){auto& t=f.bundle.whole;auto it=ref.find(st.erased);if(it==ref.end())throw std::logic_error("generator erases absent identity");if(it==ref.begin()||f.bundle.domain.slot(std::prev(it)->first)!=f.bundle.domain.slot(st.erased))++t.head_erases;ref.erase(it);it=ref.lower_bound(st.added.first);if(it==ref.end()||f.bundle.domain.slot(it->first)!=f.bundle.domain.slot(st.added.first))++t.tail_inserts;if(!ref.insert(st.added).second)throw std::logic_error("duplicate generator identity");ordinal+=2;
 if(st.query){auto ans=ref_range(ref,st.lo,st.hi);st.expected_hash=udriver::hash_records(ans);st.expected_count=ans.size();f.expected.push_back({++ordinal,std::move(ans)});++t.queries;t.returned+=st.expected_count;++seg.queries;seg.returned+=st.expected_count;seg.query_hash=udriver::mix(seg.query_hash,st.expected_hash);}t.hash=udriver::phase_mix_step(t.hash,st);seg.request_hash=udriver::phase_mix_step(seg.request_hash,st);t.steps.push_back(st);}
inline void finish_fixture(Fixture& f,const std::map<std::uint64_t,std::uint64_t>& ref){auto& t=f.bundle.whole;t.final.assign(ref.begin(),ref.end());t.hash=udriver::mix(t.hash,udriver::hash_records(t.final));if(t.steps.size()!=f.bundle.request.units)throw std::logic_error("generator U mismatch");}
inline Fixture make_synthetic(CaseSpec s,unsigned seed,bool engineering){require_sha(protocol_path(),protocol_sha);const auto generator_before=sha_file(generator_path());Fixture f;f.case_id=s.id;f.engineering=engineering;auto& b=f.bundle;b.domain={UINT64_C(1)<<40,4096};auto& r=b.request;r.seed=seed;r.initial=s.buckets*s.n;r.units=s.units;r.days=0;r.month="synthetic";r.workload=s.pattern;r.dataset_sha=protocol_sha;r.protocol_sha=protocol_sha;b.source_rows=r.initial;b.query_period=s.q?s.q:s.units+1;b.cancel_period=s.c;
 std::uint64_t identity=1;for(std::size_t slot=0;slot<s.buckets;++slot)for(std::size_t j=0;j<s.n;++j){Record rec{slot*b.domain.stride+identity,identity};if(b.domain.slot(rec.first)!=slot)throw std::logic_error("synthetic slot mapping");b.whole.initial.push_back(rec);++identity;}init_geometry(b);b.whole.hash=udriver::mix(b.whole.hash,udriver::hash_records(b.whole.initial));std::map<std::uint64_t,std::uint64_t> ref(b.whole.initial.begin(),b.whole.initial.end());auto tag=s.pattern=="low"?1:s.pattern=="high"?2:s.pattern=="prefix"?3:s.pattern=="endpoint"?4:5;auto rng=synthetic_rng(seed,tag);std::uint64_t ordinal=0;
 std::vector<std::size_t> lengths=s.pattern=="mechanism"?std::vector<std::size_t>{32768,16384,32768,16384,32768}:std::vector<std::size_t>{s.units};
 const std::array<const char*,5> names{{"A_hot","idle1","B_hot","idle2","A_return"}};
 std::size_t begin=0;for(std::size_t phase=0;phase<lengths.size();++phase){PhaseSegment seg;seg.begin=begin;seg.end=begin+lengths[phase];seg.name=lengths.size()==1?s.pattern:names[phase];seg.query_period=b.query_period;seg.cancel_period=s.c;
  for(std::size_t local=0;local<lengths[phase];++local){std::size_t slot=s.pattern=="competition"?local%64:0;bool endpoint=s.pattern=="endpoint";if(s.pattern=="mechanism"){endpoint=phase==1||phase==3;slot=endpoint?0:(phase==2?32:0)+local%32;}
   auto base=ref.lower_bound(slot*b.domain.stride);auto after=ref.lower_bound((slot+1)*b.domain.stride);if(static_cast<std::size_t>(std::distance(base,after))!=s.n)throw std::logic_error("synthetic per-bucket fixed size");std::size_t rank=1;if(!endpoint){std::uniform_int_distribution<std::size_t> choose(s.pattern=="low"?2:(s.n+3)/4,s.pattern=="low"?8:3*s.n/4);rank=choose(rng);}auto chosen=base;std::advance(chosen,rank-1);Step st;st.erased=chosen->first;st.added=endpoint?Record{slot*b.domain.stride+identity,identity}:Record(*chosen);if(endpoint)++identity;if(st.added.second>=b.domain.stride)throw std::overflow_error("fresh identity exhausted");
   if(s.q&&(local+1)%s.q==0){st.query=true;auto lo=base;std::advance(lo,3*s.n/4-1);auto hi=lo;std::advance(hi,8);st.lo=lo->first;st.hi=hi->first;}append_step(f,seg,st,ref,ordinal);}
  b.segments.push_back(seg);begin=seg.end;}
 finish_fixture(f,ref);require_sha(generator_path(),generator_before);require_sha(protocol_path(),protocol_sha);return f;}
inline Fixture synthetic_fixture(const std::string& id,unsigned seed){if(seed<94001||seed>94002)throw std::invalid_argument("test seed only");return make_synthetic(case_spec(id),seed,true);}
inline Fixture engineering_fixture(std::size_t n,std::size_t units){return make_synthetic({"ENGINEERING","prefix",1,n,units,1,0},94001,true);}
inline Fixture public_fixture(const std::string& id,unsigned seed,const CaseSpec* engineering_scale=nullptr){auto s=engineering_scale?*engineering_scale:case_spec(id);if(!s.public_data)throw std::invalid_argument("public case required");require_sha(protocol_path(),protocol_sha);const auto generator_before=sha_file(generator_path());auto physical=load_public_verified();auto sorted=physical;std::sort(sorted.begin(),sorted.end());Fixture f;f.case_id=id;f.engineering=seed>=94001&&seed<=94002;auto& b=f.bundle;b.domain={2964618,2678400};auto& r=b.request;r.seed=seed;r.initial=s.n;r.units=s.units;r.days=31;r.month="2024-01";r.data=path_utf8(public_path());r.workload=s.pattern;r.dataset_sha=dataset_sha;r.protocol_sha=protocol_sha;b.source_rows=sorted.size();b.query_period=s.q;b.cancel_period=s.c;b.ordered=id!="F04";
 std::mt19937_64 start(id=="F04"?UINT64_C(0x6249037adf150be1)+std::uint64_t(seed)*104729:7817329ULL+std::uint64_t(seed)*104729);std::uniform_int_distribution<std::uint64_t> startdist(0,sorted.size()-s.n-s.units);auto& t=b.whole;t.start=startdist(start);t.initial.assign(sorted.begin()+t.start,sorted.begin()+t.start+s.n);init_geometry(b);t.hash=udriver::mix(t.hash,udriver::hash_records(t.initial));std::map<std::uint64_t,std::uint64_t> ref(t.initial.begin(),t.initial.end());std::vector<unsigned char> alive(s.n,1);std::size_t oldest=0;std::uint64_t ordinal=0,water=t.initmax;
 auto cancel=id=="F04"?std::mt19937_64(UINT64_C(0x81ec39b7526a04df)^(std::uint64_t(seed)*104729)):std::move(start);std::mt19937_64 shuffle(UINT64_C(0x35710df29a48b6ce)+std::uint64_t(seed)*130363);
 std::vector<std::size_t> lengths=id=="F04"?std::vector<std::size_t>{87381,87381,87382}:std::vector<std::size_t>{s.units};std::size_t begin=0;
 for(std::size_t phase=0;phase<lengths.size();++phase){PhaseSegment seg;seg.name=id=="F04"?(phase==0?"sparse_before":phase==1?"shuffle":"sparse_after"):s.pattern;seg.begin=begin;seg.end=begin+lengths[phase];seg.query_period=id=="F04"?(phase==1?8:256):s.q;seg.cancel_period=id=="F04"?(phase==1?0:256):s.c;seg.shuffle_incoming=seg.random_every_delete=id=="F04"&&phase==1;std::vector<Record> incoming(sorted.begin()+t.start+s.n+seg.begin,sorted.begin()+t.start+s.n+seg.end);if(seg.shuffle_incoming)std::shuffle(incoming.begin(),incoming.end(),shuffle);
  for(std::size_t local=0;local<incoming.size();++local){while(oldest<s.n&&!alive[oldest])++oldest;if(oldest==s.n)throw std::logic_error("old-alive exhausted");auto pos=oldest;if(seg.random_every_delete||(seg.cancel_period&&(local+1)%seg.cancel_period==0)){std::uniform_int_distribution<std::size_t> remaining(oldest,s.n-1);do{pos=remaining(cancel);}while(!alive[pos]);}alive[pos]=0;Step st;st.erased=t.initial[pos].first;st.added=incoming[local];water=std::max(water,st.added.first/b.domain.stride);if((local+1)%seg.query_period==0){st.query=true;st.hi=(water+1)*b.domain.stride;st.lo=(water+1>60?water+1-60:0)*b.domain.stride;}append_step(f,seg,st,ref,ordinal);}b.segments.push_back(seg);begin=seg.end;}
 finish_fixture(f,ref);require_sha(generator_path(),generator_before);require_sha(public_path(),dataset_sha);require_sha(protocol_path(),protocol_sha);return f;}
inline Fixture registered_fixture(const std::string& id,unsigned seed,const std::string& profile){validate_registered(id,seed,profile);auto s=case_spec(id);auto f=s.public_data?public_fixture(id,seed):make_synthetic(s,seed,false);f.profile=profile;f.engineering=false;return f;}
inline std::string record_sha(const std::vector<Record>& v){SHA256 sha;for(auto r:v){sha.u64(r.first);sha.u64(r.second);}return sha.finish();}
inline void write_expected(const std::filesystem::path& path,const std::vector<Expected>& v){if(std::filesystem::exists(path))throw std::runtime_error("immutable expected already exists");std::ofstream out(path,std::ios::binary);out.write("S0EXP001",8);auto u64=[&](std::uint64_t n){char bytes[8];for(unsigned j=0;j<8;++j)bytes[j]=char(n>>(8*j));out.write(bytes,8);};for(const auto& q:v){u64(q.api_ordinal);u64(q.records.size());for(auto r:q.records){u64(r.first);u64(r.second);}}out.close();if(!out)throw std::runtime_error("expected write failed");}
inline std::vector<Expected> read_expected(const std::filesystem::path& path,std::uint64_t queries){std::ifstream in(path,std::ios::binary);char magic[8];in.read(magic,8);if(!in||std::memcmp(magic,"S0EXP001",8))throw std::runtime_error("expected schema mismatch");auto u64=[&](){char bytes[8];in.read(bytes,8);if(!in)throw std::runtime_error("expected truncated");std::uint64_t n=0;for(unsigned j=0;j<8;++j)n|=std::uint64_t(static_cast<unsigned char>(bytes[j]))<<(8*j);return n;};std::vector<Expected> v;v.reserve(queries);for(std::uint64_t i=0;i<queries;++i){Expected q;q.api_ordinal=u64();auto n=u64();if(n>100000000)throw std::runtime_error("expected count bound");q.records.resize(n);for(auto& r:q.records){r.first=u64();r.second=u64();}v.push_back(std::move(q));}char extra;if(in.get(extra))throw std::runtime_error("expected trailing bytes");return v;}
inline std::string json_quote(const std::string& s){std::string out="\"";for(unsigned char c:s){if(c=='\"'||c=='\\')out+='\\';if(c=='\n')out+="\\n";else if(c=='\r')out+="\\r";else if(c=='\t')out+="\\t";else out+=char(c);}return out+'\"';}
inline void write_fixture(const Fixture& f,const std::filesystem::path& dir){if(std::filesystem::exists(dir))throw std::runtime_error("immutable cache destination exists");require_sha(protocol_path(),protocol_sha);if(f.bundle.request.dataset_sha==dataset_sha)require_sha(public_path(),dataset_sha);auto generator=sha_file(generator_path());std::filesystem::create_directories(dir);auto cp=dir/"cache.bin",ep=dir/"cache.expected.bin";frozen_write_cache(cp,f.bundle);write_expected(ep,f.expected);auto csha=sha_file(cp),esha=sha_file(ep);auto& b=f.bundle;std::ofstream meta(dir/"cache.meta.json");meta<<"{\n\"schema\":\"S1.cache.v1\",\"case_id\":"<<json_quote(f.case_id)<<",\"profile\":"<<json_quote(f.profile)<<",\"engineering_only\":"<<(f.engineering?"true":"false")<<",\"seed\":"<<b.request.seed<<",\"N\":"<<b.request.initial<<",\"U\":"<<b.request.units<<",\"domain\":{\"stride\":"<<b.domain.stride<<",\"span\":"<<b.domain.span<<"},\"phase_lengths\":[";for(std::size_t j=0;j<b.segments.size();++j){if(j)meta<<',';meta<<b.segments[j].end-b.segments[j].begin;}meta<<"],\"q\":"<<(f.case_id=="F04"?0:(b.query_period>b.request.units?0:b.query_period))<<",\"c\":"<<b.cancel_period<<",\"phase_q\":[";for(std::size_t j=0;j<b.segments.size();++j){if(j)meta<<',';meta<<(b.segments[j].query_period>b.request.units?0:b.segments[j].query_period);}meta<<"],\"phase_c\":[";for(std::size_t j=0;j<b.segments.size();++j){if(j)meta<<',';meta<<b.segments[j].cancel_period;}meta<<"],\"API_calls\":"<<2*b.request.units+b.whole.queries<<",\"queries\":"<<b.whole.queries<<",\"source_rows\":"<<b.source_rows<<",\"month\":"<<json_quote(b.request.month)<<",\"days\":"<<b.request.days<<",\"ordered\":"<<(b.ordered?"true":"false")<<",\"dataset_sha\":"<<json_quote(b.request.dataset_sha)<<",\"protocol_sha\":"<<json_quote(b.request.protocol_sha)<<",\"generator_sha\":"<<json_quote(generator)<<",\"cache_sha\":"<<json_quote(csha)<<",\"expected_sha\":"<<json_quote(esha)<<",\"initial_sha\":"<<json_quote(record_sha(b.whole.initial))<<",\"final_sha\":"<<json_quote(record_sha(b.whole.final))<<",\"selection_input_identity\":"<<json_quote(f.case_id+":"+std::to_string(b.request.seed)+":"+csha)<<"}\n";meta.close();if(!meta)throw std::runtime_error("metadata write failed");require_sha(cp,csha);require_sha(ep,esha);require_sha(generator_path(),generator);require_sha(protocol_path(),protocol_sha);if(b.request.dataset_sha==dataset_sha)require_sha(public_path(),dataset_sha);}
inline bool cache_roundtrip(const Fixture& f,const std::string& out){if(sha_text("abc")!="ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")return false;write_fixture(f,std::filesystem::u8path(out));auto dir=std::filesystem::u8path(out);auto before=sha_file(dir/"cache.bin"),expected=sha_file(dir/"cache.expected.bin");auto b=frozen_read_cache(dir/"cache.bin");auto refs=read_expected(dir/"cache.expected.bin",b.whole.queries);require_sha(dir/"cache.bin",before);require_sha(dir/"cache.expected.bin",expected);if(b.whole.hash!=f.bundle.whole.hash||b.request.units!=f.bundle.request.units||b.segments.size()!=f.bundle.segments.size()||b.whole.initial!=f.bundle.whole.initial||b.whole.final!=f.bundle.whole.final||refs.size()!=f.expected.size())return false;for(std::size_t j=0;j<refs.size();++j)if(refs[j].api_ordinal!=f.expected[j].api_ordinal||refs[j].records!=f.expected[j].records)return false;return true;}
}
